package coderule1.dal.dao;

import coderule1.dal.model.CodeTarget;
import coderule1.dal.model.CodeTargetExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CodeTargetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int countByExample(CodeTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int deleteByExample(CodeTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer targetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int insert(CodeTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int insertSelective(CodeTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    List<CodeTarget> selectByExample(CodeTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    CodeTarget selectByPrimaryKey(Integer targetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CodeTarget record, @Param("example") CodeTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CodeTarget record, @Param("example") CodeTargetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeTarget record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeTarget record);


    List<CodeTarget> selectAllTarget();

    int saveOrUpdate(CodeTarget record);

    String getRuleByKeyWorld(@Param("targetCode") String targetCode);
}