package coderule1.dal.dao;

import coderule1.dal.model.CodeLittlerule;
import coderule1.dal.model.CodeLittleruleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CodeLittleruleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int countByExample(CodeLittleruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int deleteByExample(CodeLittleruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer littleruleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int insert(CodeLittlerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int insertSelective(CodeLittlerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    List<CodeLittlerule> selectByExample(CodeLittleruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    CodeLittlerule selectByPrimaryKey(Integer littleruleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CodeLittlerule record, @Param("example") CodeLittleruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CodeLittlerule record, @Param("example") CodeLittleruleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CodeLittlerule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_littlerule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CodeLittlerule record);

    int updateSeqByPrimaryKey(@Param("seqValue")int seqValue,@Param("littleruleid")int littleruleid);

    Map<String,Object> getSeqByPrimaryKey(int littleruleid);

    List<Map<String,String>> getIdWithExplain(@Param("inSql") String inSql);

    List<CodeLittlerule> getLittleRuleByClass(@Param("typeClass") String typeClass);
}