package coderule1.dal.model;

public class CodeLittlerule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.littleRuleid
     *
     * @mbggenerated
     */
    private Integer littleruleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.littleRuleName
     *
     * @mbggenerated
     */
    private String littlerulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.fkBigRule
     *
     * @mbggenerated
     */
    private Integer fkbigrule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.fkTargetId
     *
     * @mbggenerated
     */
    private Integer fktargetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.typeClass
     *
     * @mbggenerated
     */
    private String typeclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.conditionalValue
     *
     * @mbggenerated
     */
    private String conditionalvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.spacer
     *
     * @mbggenerated
     */
    private String spacer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_littlerule.param
     *
     * @mbggenerated
     */
    private String param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.littleRuleid
     *
     * @return the value of code_littlerule.littleRuleid
     *
     * @mbggenerated
     */
    public Integer getLittleruleid() {
        return littleruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.littleRuleid
     *
     * @param littleruleid the value for code_littlerule.littleRuleid
     *
     * @mbggenerated
     */
    public void setLittleruleid(Integer littleruleid) {
        this.littleruleid = littleruleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.littleRuleName
     *
     * @return the value of code_littlerule.littleRuleName
     *
     * @mbggenerated
     */
    public String getLittlerulename() {
        return littlerulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.littleRuleName
     *
     * @param littlerulename the value for code_littlerule.littleRuleName
     *
     * @mbggenerated
     */
    public void setLittlerulename(String littlerulename) {
        this.littlerulename = littlerulename == null ? null : littlerulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.fkBigRule
     *
     * @return the value of code_littlerule.fkBigRule
     *
     * @mbggenerated
     */
    public Integer getFkbigrule() {
        return fkbigrule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.fkBigRule
     *
     * @param fkbigrule the value for code_littlerule.fkBigRule
     *
     * @mbggenerated
     */
    public void setFkbigrule(Integer fkbigrule) {
        this.fkbigrule = fkbigrule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.fkTargetId
     *
     * @return the value of code_littlerule.fkTargetId
     *
     * @mbggenerated
     */
    public Integer getFktargetid() {
        return fktargetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.fkTargetId
     *
     * @param fktargetid the value for code_littlerule.fkTargetId
     *
     * @mbggenerated
     */
    public void setFktargetid(Integer fktargetid) {
        this.fktargetid = fktargetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.typeClass
     *
     * @return the value of code_littlerule.typeClass
     *
     * @mbggenerated
     */
    public String getTypeclass() {
        return typeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.typeClass
     *
     * @param typeclass the value for code_littlerule.typeClass
     *
     * @mbggenerated
     */
    public void setTypeclass(String typeclass) {
        this.typeclass = typeclass == null ? null : typeclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.conditionalValue
     *
     * @return the value of code_littlerule.conditionalValue
     *
     * @mbggenerated
     */
    public String getConditionalvalue() {
        return conditionalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.conditionalValue
     *
     * @param conditionalvalue the value for code_littlerule.conditionalValue
     *
     * @mbggenerated
     */
    public void setConditionalvalue(String conditionalvalue) {
        this.conditionalvalue = conditionalvalue == null ? null : conditionalvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.seq
     *
     * @return the value of code_littlerule.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.seq
     *
     * @param seq the value for code_littlerule.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.spacer
     *
     * @return the value of code_littlerule.spacer
     *
     * @mbggenerated
     */
    public String getSpacer() {
        return spacer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.spacer
     *
     * @param spacer the value for code_littlerule.spacer
     *
     * @mbggenerated
     */
    public void setSpacer(String spacer) {
        this.spacer = spacer == null ? null : spacer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_littlerule.param
     *
     * @return the value of code_littlerule.param
     *
     * @mbggenerated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_littlerule.param
     *
     * @param param the value for code_littlerule.param
     *
     * @mbggenerated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }
}