package coderule1.dal.model;

import java.util.Date;

public class CodeTarget {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.targetId
     *
     * @mbggenerated
     */
    private Integer targetid;

    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.targetCode
     *
     * @mbggenerated
     */
    private String targetcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.targetName
     *
     * @mbggenerated
     */
    private String targetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.createName
     *
     * @mbggenerated
     */
    private String createname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.targetRemark
     *
     * @mbggenerated
     */
    private String targetremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column code_target.targetRule
     *
     * @mbggenerated
     */
    private String targetrule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.targetId
     *
     * @return the value of code_target.targetId
     *
     * @mbggenerated
     */
    public Integer getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.targetId
     *
     * @param targetid the value for code_target.targetId
     *
     * @mbggenerated
     */
    public void setTargetid(Integer targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.targetCode
     *
     * @return the value of code_target.targetCode
     *
     * @mbggenerated
     */
    public String getTargetcode() {
        return targetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.targetCode
     *
     * @param targetcode the value for code_target.targetCode
     *
     * @mbggenerated
     */
    public void setTargetcode(String targetcode) {
        this.targetcode = targetcode == null ? null : targetcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.targetName
     *
     * @return the value of code_target.targetName
     *
     * @mbggenerated
     */
    public String getTargetname() {
        return targetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.targetName
     *
     * @param targetname the value for code_target.targetName
     *
     * @mbggenerated
     */
    public void setTargetname(String targetname) {
        this.targetname = targetname == null ? null : targetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.createTime
     *
     * @return the value of code_target.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.createTime
     *
     * @param createtime the value for code_target.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.createName
     *
     * @return the value of code_target.createName
     *
     * @mbggenerated
     */
    public String getCreatename() {
        return createname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.createName
     *
     * @param createname the value for code_target.createName
     *
     * @mbggenerated
     */
    public void setCreatename(String createname) {
        this.createname = createname == null ? null : createname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.targetRemark
     *
     * @return the value of code_target.targetRemark
     *
     * @mbggenerated
     */
    public String getTargetremark() {
        return targetremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.targetRemark
     *
     * @param targetremark the value for code_target.targetRemark
     *
     * @mbggenerated
     */
    public void setTargetremark(String targetremark) {
        this.targetremark = targetremark == null ? null : targetremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column code_target.targetRule
     *
     * @return the value of code_target.targetRule
     *
     * @mbggenerated
     */
    public String getTargetrule() {
        return targetrule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column code_target.targetRule
     *
     * @param targetrule the value for code_target.targetRule
     *
     * @mbggenerated
     */
    public void setTargetrule(String targetrule) {
        this.targetrule = targetrule == null ? null : targetrule.trim();
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
}