package coderule1.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CodeTargetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code_target
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code_target
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table code_target
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public CodeTargetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table code_target
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTargetidIsNull() {
            addCriterion("targetId is null");
            return (Criteria) this;
        }

        public Criteria andTargetidIsNotNull() {
            addCriterion("targetId is not null");
            return (Criteria) this;
        }

        public Criteria andTargetidEqualTo(Integer value) {
            addCriterion("targetId =", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotEqualTo(Integer value) {
            addCriterion("targetId <>", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidGreaterThan(Integer value) {
            addCriterion("targetId >", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidGreaterThanOrEqualTo(Integer value) {
            addCriterion("targetId >=", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidLessThan(Integer value) {
            addCriterion("targetId <", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidLessThanOrEqualTo(Integer value) {
            addCriterion("targetId <=", value, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidIn(List<Integer> values) {
            addCriterion("targetId in", values, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotIn(List<Integer> values) {
            addCriterion("targetId not in", values, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidBetween(Integer value1, Integer value2) {
            addCriterion("targetId between", value1, value2, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetidNotBetween(Integer value1, Integer value2) {
            addCriterion("targetId not between", value1, value2, "targetid");
            return (Criteria) this;
        }

        public Criteria andTargetcodeIsNull() {
            addCriterion("targetCode is null");
            return (Criteria) this;
        }

        public Criteria andTargetcodeIsNotNull() {
            addCriterion("targetCode is not null");
            return (Criteria) this;
        }

        public Criteria andTargetcodeEqualTo(String value) {
            addCriterion("targetCode =", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeNotEqualTo(String value) {
            addCriterion("targetCode <>", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeGreaterThan(String value) {
            addCriterion("targetCode >", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeGreaterThanOrEqualTo(String value) {
            addCriterion("targetCode >=", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeLessThan(String value) {
            addCriterion("targetCode <", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeLessThanOrEqualTo(String value) {
            addCriterion("targetCode <=", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeLike(String value) {
            addCriterion("targetCode like", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeNotLike(String value) {
            addCriterion("targetCode not like", value, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeIn(List<String> values) {
            addCriterion("targetCode in", values, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeNotIn(List<String> values) {
            addCriterion("targetCode not in", values, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeBetween(String value1, String value2) {
            addCriterion("targetCode between", value1, value2, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetcodeNotBetween(String value1, String value2) {
            addCriterion("targetCode not between", value1, value2, "targetcode");
            return (Criteria) this;
        }

        public Criteria andTargetnameIsNull() {
            addCriterion("targetName is null");
            return (Criteria) this;
        }

        public Criteria andTargetnameIsNotNull() {
            addCriterion("targetName is not null");
            return (Criteria) this;
        }

        public Criteria andTargetnameEqualTo(String value) {
            addCriterion("targetName =", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameNotEqualTo(String value) {
            addCriterion("targetName <>", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameGreaterThan(String value) {
            addCriterion("targetName >", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameGreaterThanOrEqualTo(String value) {
            addCriterion("targetName >=", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameLessThan(String value) {
            addCriterion("targetName <", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameLessThanOrEqualTo(String value) {
            addCriterion("targetName <=", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameLike(String value) {
            addCriterion("targetName like", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameNotLike(String value) {
            addCriterion("targetName not like", value, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameIn(List<String> values) {
            addCriterion("targetName in", values, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameNotIn(List<String> values) {
            addCriterion("targetName not in", values, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameBetween(String value1, String value2) {
            addCriterion("targetName between", value1, value2, "targetname");
            return (Criteria) this;
        }

        public Criteria andTargetnameNotBetween(String value1, String value2) {
            addCriterion("targetName not between", value1, value2, "targetname");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatenameIsNull() {
            addCriterion("createName is null");
            return (Criteria) this;
        }

        public Criteria andCreatenameIsNotNull() {
            addCriterion("createName is not null");
            return (Criteria) this;
        }

        public Criteria andCreatenameEqualTo(String value) {
            addCriterion("createName =", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameNotEqualTo(String value) {
            addCriterion("createName <>", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameGreaterThan(String value) {
            addCriterion("createName >", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameGreaterThanOrEqualTo(String value) {
            addCriterion("createName >=", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameLessThan(String value) {
            addCriterion("createName <", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameLessThanOrEqualTo(String value) {
            addCriterion("createName <=", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameLike(String value) {
            addCriterion("createName like", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameNotLike(String value) {
            addCriterion("createName not like", value, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameIn(List<String> values) {
            addCriterion("createName in", values, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameNotIn(List<String> values) {
            addCriterion("createName not in", values, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameBetween(String value1, String value2) {
            addCriterion("createName between", value1, value2, "createname");
            return (Criteria) this;
        }

        public Criteria andCreatenameNotBetween(String value1, String value2) {
            addCriterion("createName not between", value1, value2, "createname");
            return (Criteria) this;
        }

        public Criteria andTargetremarkIsNull() {
            addCriterion("targetRemark is null");
            return (Criteria) this;
        }

        public Criteria andTargetremarkIsNotNull() {
            addCriterion("targetRemark is not null");
            return (Criteria) this;
        }

        public Criteria andTargetremarkEqualTo(String value) {
            addCriterion("targetRemark =", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkNotEqualTo(String value) {
            addCriterion("targetRemark <>", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkGreaterThan(String value) {
            addCriterion("targetRemark >", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkGreaterThanOrEqualTo(String value) {
            addCriterion("targetRemark >=", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkLessThan(String value) {
            addCriterion("targetRemark <", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkLessThanOrEqualTo(String value) {
            addCriterion("targetRemark <=", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkLike(String value) {
            addCriterion("targetRemark like", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkNotLike(String value) {
            addCriterion("targetRemark not like", value, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkIn(List<String> values) {
            addCriterion("targetRemark in", values, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkNotIn(List<String> values) {
            addCriterion("targetRemark not in", values, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkBetween(String value1, String value2) {
            addCriterion("targetRemark between", value1, value2, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetremarkNotBetween(String value1, String value2) {
            addCriterion("targetRemark not between", value1, value2, "targetremark");
            return (Criteria) this;
        }

        public Criteria andTargetruleIsNull() {
            addCriterion("targetRule is null");
            return (Criteria) this;
        }

        public Criteria andTargetruleIsNotNull() {
            addCriterion("targetRule is not null");
            return (Criteria) this;
        }

        public Criteria andTargetruleEqualTo(String value) {
            addCriterion("targetRule =", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleNotEqualTo(String value) {
            addCriterion("targetRule <>", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleGreaterThan(String value) {
            addCriterion("targetRule >", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleGreaterThanOrEqualTo(String value) {
            addCriterion("targetRule >=", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleLessThan(String value) {
            addCriterion("targetRule <", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleLessThanOrEqualTo(String value) {
            addCriterion("targetRule <=", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleLike(String value) {
            addCriterion("targetRule like", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleNotLike(String value) {
            addCriterion("targetRule not like", value, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleIn(List<String> values) {
            addCriterion("targetRule in", values, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleNotIn(List<String> values) {
            addCriterion("targetRule not in", values, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleBetween(String value1, String value2) {
            addCriterion("targetRule between", value1, value2, "targetrule");
            return (Criteria) this;
        }

        public Criteria andTargetruleNotBetween(String value1, String value2) {
            addCriterion("targetRule not between", value1, value2, "targetrule");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table code_target
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table code_target
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}